
CREATE TABLE labour (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  daily_wage INTEGER NOT NULL,
  is_present BOOLEAN NOT NULL DEFAULT 1,
  total_pay INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_labour_name ON labour(name);
